### ISSUE TITLE
Forces naming convention or extra work?

### ISSUE THREAD

**Issue by Matt2k34** [zscaler/terraform-azurerm-zpa-app-connector-modules#7]
Firstly - thanks for the module :)

However, apologies if I'm missing something - but to me this seems an oversight. Feel free to point me in the right direction if I'm misunderstanding something.

## Describe the bug

The modules are forcing extra work during deployment, by pre-paring the environment (for BYO variables) or it forces your pre-defined naming convention (which doesn't fit our environment rules, obviously)

## Expected behavior

"automatically created" objects should be able to have the naming convention changed without having to edit the individual modules (Doing it this way - this will create an issue with longterm maintenance and management issue), or just becomes really cumbersome and fiddly when deploying with pipeline.

## Current behavior
e.g. under: "terraform-zsac-network-azure"

the resource has the line:
` name     = "${var.name_prefix}-rg-${var.resource_tag}"`

which although uses variables in the name, it forces the naming convention.

## Possible solution

Have the "name" as a variable in the root of the solution, which has a default if you don't specify anything.

## Workaround

Have a pre-script which deploys the environment, then use BYO variables (but this is pretty ... meh)

## Steps to reproduce

Try to deploy a none-BYO environment with custom object names.

## Context

Ideally the module would take input at the root which is then easy to manage and going forward as the zpa modules are updated, we can upgrade the version with little maintenance effort.

## Your Environment

Test deploying "ac" to a test environment prior to production.

I may be missing something, but it feels like an oversight on the module setup.

**Comment by willguibr** [comment]
@Matt2k34 
The request has been addressed in the latest v1.1.1 release.

Zscaler DevRel
