### ISSUE TITLE
Missing access to BETA tenant 

### ISSUE THREAD

**Issue by Timberval** [zscaler/terraform-azurerm-zpa-app-connector-modules#9]
Describe the request
I would like to request to add the connectivity for the beta tenant, allowing me to test and provide feedback on the new functionalities.
Thanks

**Comment by willguibr** [comment]
@Timberval Can you please be more specific on what you mean by "add the connectivity for the beta tenant"?
Please refer to the module READ me page here: https://github.com/zscaler/terraform-azurerm-zpa-app-connector-modules?tab=readme-ov-file#zscaler-requirements

If you still have questions, please open a case with Zscaler support, for further assistance.

Zscaler DevRel.
